export const nicoTexts = [
  "La distance que parcourt en moyenne chaque année notre pouce sur un écran est de 100 km (moyenne européenne)",
  "un smartphone ou téléphone intelligent est un téléphone mobile disposant en général d'un écran tactile capacitif multitouch, d'un capteur photographique, et de capacité d'ajouter des applications diverses telles que des fonctions d'un assistant numérique personnel et de certaines fonctions d'un ordinateur portable. il peut remplacer un appareil photographique numérique. il peut également être doté d'autres capteurs tels qu'un accéléromètre, ou la réception de signaux de positionnement par satellite. la saisie des données se fait le plus souvent à l'aide d'un écran tactile ou, plus rarement, d'un clavier ou d'un stylet",
  "pendant que les machines produisent du sens, à la chaîne, nous scrollons sans fin, hypnotisés",
  "spectateurs connectés des déchaînements du monde, observateurs observés d’une réalité mouvante et segmentée nous scrollons sans fin, hypnotisés",
  "en 2022, il s’est vendu 1,2 milliards de smartphones dans le monde. 1,3 milliards en 2023",
  "posés les uns sur les autres, écran contre écran, ils formeraient une tour d’une hauteur de 12500km de hauteur",
  "dès 2010, la chercheuse américaine Sarah T. Roberts s’est intéressée à la question de la modération sur les plateformes. elle découvre alors un univers professionnel effarant : les éboueurs du web. ce sont les personnes chargées de vérifier et supprimer les publications signalées. scènes de viols, meurtres, décapitations, tortures, suicides, tout ce que le web compte de plus affreux. ces employés, souvent des jeunes femmes, mal payées, connaissent un taux de dépression et de suicide très élevé",
  "le premier téléphone présenté comme un smartphone, a été commercialisé en 2000",
  "le premier iPhone est commercialisé en juin 2007",
  "facebook est fondé en 2004 par Mark Zuckerberg, Chris Hughes, Eduardo Saverin, Andrew McCollum et Dustin Moskovitz à l'université Harvard",
  "instagram est fondé en 2010 par Kevin Systrom et Mike Krieger. ce réseau social compte aujourd’hui plus de 2 milliards d’utilisateurs",
  "70 kg de matières premières sont nécessaires pour produire, utiliser et éliminer un seul smartphone ",
  "plus de 60 matériaux, sur les 103 éléments du tableau périodique de Mendeleïev, entrent dans la composition d’un smartphone. parmi eux, une grande majorité sont identifiés comme « critiques » par l’Union européenne",
  "magnésium bismuth gallium germanium  ruthénium rhodium platine tantale cobalt béryllium niobium lithium hafnium",
  "13 000 litres d’eau sont nécessaires à la fabrication d’un smartphone de 135 grammes",
  "un enfant de moins de 11 ans passe en moyenne 1 heure par jour sur un smartphone. pour un adolescent, cela monte à 4 heures quotidiennes pendant les vacances, 5 heures même durant le week-end",
  "manquer une notification peut stimuler le syndrome FOMO (Fear of missing out), qui traduit la peur de rater quelque chose et pousse les personnes à rester connectées en permanence pour être présentes à tous les événements",
  "chez les adultes, l’utilisation des écrans est souvent justifiée par des impératifs professionnels ou par la gestion de tâches du quotidien. cependant, la frontière entre usage utile et distraction devient floue. un adulte peut commencer par vérifier ses e-mails professionnels pour finalement passer une heure sur Instagram ",
  "70 % des utilisateurs préfèrent utiliser leur smartphone plutôt qu’un ordinateur pour effectuer une recherche sur Internet. de plus en plus élevé, ce chiffre témoigne de l’impact des supports mobiles sur la consommation d’Internet",
  "la durée de vie d’un satellite Starlink est théoriquement de 5 ans. 3 ans, en réalité",
  "les satellites Starlink sont lancés en orbite par lots de 15 à 56 unités. début 2024, il y avait  près de 6000 satellites Starlink en orbite. à terme, SpaceX prévoit de construire une constellation massive de 12 000 satellites, avec une expansion possible à 42 000 satellites plus tard",
  "un smartphone a une espérance de vie moyenne de 3 ans",
  "TikTok es ahora la principal plataforma para la difusión de redes machistas y basadas en la identidad",
  "63 % des Français conservent leur smartphone moins de deux ans",
  "obsolescence programmée, obsolescence mécanique, obsolescence logicielle",
  "en 2023, 84,7% des 15-24 ans, soit 6,6 millions de jeunes, se sont connectés chaque jour à internet. ils y passent en moyenne 3h50 par jour, dont 3h34 sur leur téléphone mobile. les réseaux sociaux représentent 58% de leur temps en ligne",
  "60% des 18-25 ans déclarent avoir déjà été confrontés à une situation de cyberharcèlement",
  "en octobre 2022, Elon Musk rachète le réseau social Twitter qu’il rebaptise X. le montant de la transaction s’élève à 44 milliards de dollars",
  "l'introduction en bourse de Facebook a lieu le 17 mai 2012 au prix de 38 $ US. la société est alors évaluée à 104 milliards de dollars",
  "en décembre 2022, Meta accepte de payer 725 millions de dollars à la justice américaine pour mettre fin au procès lancé en 2018 concernant le scandale Cambridge Analytica",
  "Tiktok est aujourd’hui la plateforme principale de diffusion des réseaux masculinistes et identitaires",
  "en 2022, TikTok totalise 1,7 milliard d'utilisateurs actifs dans le monde",
  "in 2022, 1.2 billion smartphones were sold worldwide. 1.3 billion in 2023",
  "la version internationale de Tiktok a réussi à supplanter Snapchat ou Twitter en s’imposant comme le réseau social le plus addictif",
  "nudité adulte, fake news, pornographie, images violentes, viols, discours haineux, Facebook déclare, en 2018, prendre le plus grand soin de ses éboueurs du Web",
  "en 2024, les datacenters du groupe Meta ont consommé 14 975 435 MWh, en augmentation de 34% par rapport à l’année précédente. un bond qui serait imputable à l'adoption de l'IA par le groupe",
  "les data centers représentent aujourd’hui 3% de la consommation électrique mondiale, cette consommation équivaut à celle d’un pays comme l’Argentine ou la Pologne",
  "même lorsqu’il est en veille, un serveur Web consomme en moyenne 100 watts afin de répondre instantanément à une éventuelle requête",
  "dans un article paru dans la revue Australasian Journal of Philosophy en juin 2025, les chercheurs Rachael L. Brown et Rob Brooks comparent les smartphones à des corps parasitaires, au sens biologique du terme, faisant de nous les hôtes désormais physiologiquement dépendants de ces outils technologiques",
];
